### ISSUE TITLE
Timeout during make apply

### ISSUE THREAD

**Issue by estahn** [cloudfoundry-community/terraform-aws-cf-install#25]
```
aws_instance.bastion (remote-exec): . Failed: Connection timed out - connect(2) for "community-shared-boshreleases.s3.amazonaws.com" port 443 (00:02:07)

aws_instance.bastion (remote-exec): Error 100: Connection timed out - connect(2) for "community-shared-boshreleases.s3.amazonaws.com" port 443
```

**Comment by teancom** [comment]
This is due to using the released 0.3.7 version of terraform. There is a fix in hashicorp/terraform's HEAD, or you can use the version specified in our README. Alternatively, you can manually fix your NAT instance by going into the AWS console, right-clicking on the instance, and turning off source/dest checking (but of course having a manual step kinda defeats the purpose of terraform).

**Comment by teancom** [comment]
BTW, the terraform issue: https://github.com/hashicorp/terraform/issues/1020
Known good terraform version: https://github.com/hashicorp/terraform/commit/fd6382fbafe0be8547eabbb279bbb6f095c87096

**Comment by estahn** [comment]
@teancom Thanks. I will check is out.
